# Generated by Django 4.2.6 on 2023-11-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labware_app', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=100),
        ),
    ]
