# Generated by Django 4.2.6 on 2023-11-03 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labware_app', '0004_orders_orderupdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
        migrations.DeleteModel(
            name='OrderUpdate',
        ),
    ]
