# Generated by Django 4.2.6 on 2023-11-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labware_app', '0005_delete_orders_delete_orderupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='ph_num',
            field=models.IntegerField(),
        ),
    ]
