# Generated by Django 4.2.6 on 2023-11-14 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labware_app', '0006_alter_contact_ph_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
